# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Github
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: commit
          committer_branch: metrics

          user: ForumPlayer
          template: classic
          base: header, repositories
          config_timezone: America/Sao_Paulo
          config_order: base.header, base.repositories, languages, notable, habits
          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200

      - name: Gists
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: gists-metrics.svg
          output_action: commit
          committer_branch: metrics

          user: ForumPlayer
          template: classic
          base: gists
          config_timezone: America/Sao_Paulo
          plugin_gists: yes

      - name: Music
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: music-metrics.svg
          output_action: commit
          committer_branch: metrics
          base: ""
          plugin_music: yes
          plugin_music_limit: 4
          plugin_music_playlist: https://music.youtube.com/playlist?list=PLE3UaS8PyVTqi-U8J_GJuMsFQpt3Ug-Aw
          plugin_music_provider: youtube
          plugin_music_time_range: short
          plugin_music_top_type: tracks
          plugin_music_user: .user.login

      - name: Anilist
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: anilist-metrics.svg
          output_action: commit
          committer_branch: metrics
          base: ""
          plugin_anilist: yes
          plugin_anilist_limit: 1
          plugin_anilist_limit_characters: 11
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, characters
          plugin_anilist_shuffle: yes
          plugin_anilist_user: ForumPlayer

      - name: Wakatime
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: wakatime-metrics.svg
          output_action: commit
          committer_branch: metrics
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_days: 7
          plugin_wakatime_limit: 5
          plugin_wakatime_sections: time, projects, languages, editors, os
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: ForumPlayer
